### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [mathisdt/trackworktime#125]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by mathisdt** [comment]
Thanks for the hint! I should update the screenshots anyway, so I also can provide them to both **Google Play Store** and **F-Droid**.

**Comment by mondlicht-und-sterne** [comment]
if you have entered this, you can also close the issue. thank you, it would look more beautiful.
