### ISSUE TITLE
Track by WiFi not working

### ISSUE THREAD

**Issue by andrearicci** [mathisdt/trackworktime#128]
Hi and thank you for the software.
The WiFi start/stop event is not working for me. Is maybe there some privileges I have to give to the app? autostart or something? I opened the app in the afternoon but id didn't recognised when I left the office.
Maybe an option to select a SSID from the curren ones (instead of writing it down) could help to avoid typos - a sort of "work here" for geolocation.
Thank you again

**Comment by mathisdt** [comment]
Thanks for the report! Which version are you using - an APK from Play Store / F-Droid or a self-built APK from the current master branch?

Maybe Android forbids the app to do work in the background (to save battery), please use the menu item "disable restrictions" to allow it. The necessary privileges for the app and their justification is explained [here](https://zephyrsoft.org/trackworktime/privacy). You can use Android's settings to check if TWT has these privileges.

**Comment by andrearicci** [comment]
I have 1.0.6, installed with F.Droid. It had the  battery saving setting on, now I switched it off. Curiously on MIUI 11.0.2 there are contraddictory options - I found another battery saver still on, and diffrent privileges are found in different places, with different names (and different from the tecnical specs you linked). So I'll try them one by one.  I'll let you know. 

Wish: in the options I'd like to see the current settings, other than the sample (eg: current latitude and longitude, current SSID...)
Thank you for the software and your quick replay.

**Comment by mathisdt** [comment]
> Wish: in the options I'd like to see the current settings, other than the sample (eg: current latitude and longitude, current SSID...)

Spoiler: Your wish is about to come true, I plan to release the next version very soon, and @dliw already implemented what you asked for!

**Comment by mathisdt** [comment]
Hi @andrearicci, did anything help? If so, please share your insights - others who have the same problems might profit.

**Comment by andrearicci** [comment]
Hi @mathisdt, I have a Xiaomi redmi Note 4, and my main problem is to find a correspondance between Miui permissions (translated to Italian) and the ones required by the app. I managed to set "automatic start-up". I wonder if RECEIVE_BOOT_COMPLETED is the same as automatic startup, anyway, now the app discovers the wifi, but late - it takes also 1/2 hour in office before it starts, so when I exit. 
I just now set "no battery restrictions" (I understund that Miui has his own battery saver system) and I'll check it tomorrow. 
Thank you.

**Comment by andrearicci** [comment]
Now it's working. I had the gps too but it was too imprecise

**Comment by mathisdt** [comment]
Great to hear, thanks for the feedback. The app doesn't use GPS but only radio cell triangulation as alternative position tracking option - this has an advantage (the battery is not drained) but also a disadvantage (it's not as exact as GPS). If you like, you can also use Llama or Tasker for the geo-fencing. More info about that on https://zephyrsoft.org/trackworktime .
