### ISSUE TITLE
wish: IN and OUT for single event

### ISSUE THREAD

**Issue by andrearicci** [mathisdt/trackworktime#129]
Hi, the manual editing of events is a bit tedious: I hav to create an IN event and thena an OUT event. Wouldn't be better to create single events with a star and ending time each?
Thank you

**Comment by mathisdt** [comment]
This could be implemented via a new option next to the menu item "new event" on the event list screen, e.g. "new period" which would open a screen to enter this data:
- a date
- a start time
- an end time
- a task
- a hint text (optionally)

**Comment by mathisdt** [comment]
This feature is going to be part of the next release.
