### ISSUE TITLE
report: off-by-one error in daily time aggregation

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#133]
When creating reports with daily aggregation, an off-by-one error appears. Each time is attributed to the day before it was actually tracked.

Example with home timezone "Europe/Berlin":

Tracked time:
![time-tracked](https://user-images.githubusercontent.com/1932462/106520673-6b8ec200-64dd-11eb-9a59-4b89d68acdc1.png)

Generate report (1):
![report-current-week](https://user-images.githubusercontent.com/1932462/106520707-7a757480-64dd-11eb-8dfb-ee184a5e69ed.png)

Report file (1):
![report-current-week-result](https://user-images.githubusercontent.com/1932462/106520895-bdcfe300-64dd-11eb-89ae-ddfaf63dff51.png)

Generate report (2):
![report-last-and-current-week](https://user-images.githubusercontent.com/1932462/106520910-c45e5a80-64dd-11eb-9ace-d4fe8c96df71.png)

Report file (2):
![report-last-and-current-week-result](https://user-images.githubusercontent.com/1932462/106520934-cc1dff00-64dd-11eb-8703-aafe7276bc5a.png)

**Comment by mathisdt** [comment]
@dliw If you have time, could you have a look into this?

**Comment by mathisdt** [comment]
Just came to my mind: maybe this is also a problem in weekly/monthly/yearly aggregation...

**Comment by dliw** [comment]
Yes, this is a general problem, because the time frames were relative to the current time and not the start of the day. See my pull request.
