### ISSUE TITLE
rework storage access for Android 10+ (due by May 5th, 2021)

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#139]
Find a way to save the app's files with the new restrictions on storage access, e.g.
- logs files
- backups
- automatic backups

See also:
- https://developer.android.com/about/versions/11/privacy/storage#scoped-storage
- https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage

**Comment by mathisdt** [comment]
For publishing in Google Play, targeting API level 30 will be mandatory beginning in November 2021.

**Comment by mathisdt** [comment]
I just learned that this is already required for any updates published via Play store from May 5th, 2021 on.

Also see https://support.google.com/googleplay/android-developer/answer/10467955 for details.

**Comment by mathisdt** [comment]
Thoughts:

1. log files: can be put into the app's internal data directory [a], but there should be a possibility to export the logs manually if a user wants to [b]
2. automatic backups: can also be put into the app's internal data directory [a], but there should be a possibility to export them if a user wants to restore from them [b]
3. manual backups: this is triggered by the user, so the user has to choose a target location [b]
    * when restoring from a backup, the user has to be asked for the backup file to restore [c]

**Generally, backups should be converted to a one-file package.** Maybe a ZIP file of the backup CSV files, or a text format which contains the CSV files concatenated (but separated by a special line or header). Probably the ZIP approach is more resilient and also more future-proof (if another backup CSV file is added later, for instance).

[a] https://developer.android.com/training/data-storage/app-specific#internal-access-files
[b] https://developer.android.com/training/data-storage/shared/documents-files#create-file
[c] https://developer.android.com/training/data-storage/shared/documents-files#open-file

**Comment by WildOrangutan** [comment]
I will start by moving logging to internal storage.

> 2. automatic backups: can also be put into the app's internal data directory [a], but there should be a possibility to export them if a user wants to restore from them [b]

I think some users sync backup file with cloud storage. Doing this would prevent them doing that. Maybe backup files could be saved to public documents directory.

**Comment by mathisdt** [comment]
You're welcome to start tackling this! Without the changes outlined above, no app update can be distributed via Play store. The policy (effective since May 5th, 2021) forbids doing what TWT does at the moment, at least for newly uploaded packages.

I'm one of the users syncing backup files with my private cloud myself! If you find a way to put the data to the documents directory without the user having to approve it every time, please implement it. I was kind of lost when I read the documentation...
