### ISSUE TITLE
Notification: Make "possible finishing time" take flexi time into account

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#140]
Looking at persistent [notification](https://user-images.githubusercontent.com/5972966/108354069-3a0a3c00-71e9-11eb-87b9-9da4b17f26f4.png), while clocked in. 
I think it could be nice to take into account current flexi time value.

For example, if your flexi is -1:00 from yesterday, it could offset "possible finishing time" by +1:00 for today.

App version: 1.0.7

**Comment by mathisdt** [comment]
This is already implemented, in the options you can enable these three checkboxes:
- notification enabled
- use flexi time 0:00 as target
- countdown to 0:00 every day

If you only enable the first two, the will reduce only the last working day of the week by the flexi overtime. If you check all three, it will do this every day.
