### ISSUE TITLE
Documentation neded for the new flex time scheme - how to enter holidays and free days

### ISSUE THREAD

**Issue by benedetto** [mathisdt/trackworktime#142]
With version 1.1.0 the new target time scheme replaced the flex time event. However, I could not find out how to fix the flex time for days that are free due to public holidays, vacation days or the like. I could not find any documentation on that so far.

It would be great if such a documentation could be provided or, if it already exists, I could be pointed to it.

**Comment by mathisdt** [comment]
First of all, thanks for your feedback! I agree that it's not as intuitive as it could be, but we found no better place for it yet than a tap on the date in the main table.

This is documented in the first screenshot in [Play Store](https://play.google.com/store/apps/details?id=org.zephyrsoft.trackworktime) and [F-Droid](https://f-droid.org/packages/org.zephyrsoft.trackworktime/) and it's also mentioned in the "About" text inside the app (third paragraph: "The app enables you to modify the planned working time effortlessly - just tap on the date you want to edit in the main table.").

If you know a way this could be communicated better: please share it, we value contributions.

**Comment by benedetto** [comment]
@mathisdt First of all: Thanks a lot, it works.

Now I can also see the 2.5 reasons why I didn't find it myself:
1. Regarding UI: For me it wasn't obvious, that hitting the date brings me somewhere else than hitting any other spot in a row of the date table – especially, since there is no optical separation between the dates and the rest of the line. Maybe giving the date and the "rest" columns different background colours (slightly brighter and darker) might give the user a hint, that those have different functionalities.
2. (and a half) Regarding documentation: both the sceenshots as well as the about section are places where I would have expected hints on usage. For me, the screenshots in the app stores normally are just a preview on what the app looks like, which different screens it has and so on, i.e. more of an advertisement than documentation. The same goes for the "About" section, where I also typically expect "what" the app can do /something along the lines of "with this app, you can draw unicorns, summon daemons and ride lightnings") but not "how" to do this, i.e. which buttons to click and dates to enter... For the how, I would be searching for something like a "help" or "howto" menu entry.

If you intend to change something about the points above and need some feedback or input, don't hesitate to give me a ping. I would be happy to help if I can.

**Comment by mathisdt** [comment]
I already included the second proposition in the just released version 1.1.6, the "About" item is now called "About / Help", and on top of the "About / Help" text there is a link to a FAQ on the app's web site where I will put the questions which seem to bother the users most (e.g. your initial question in this ticket). This web site will be easier to update than the app itself, so I can react more quickly.
