### ISSUE TITLE
Edit events: Show task name

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#151]
Would it be possible to add task number to "Edit events" screen. I feel like it would be nice, to get bit better overview of tasks.

Did some quick mockup, please see image. I moved date to title row, so there's more space for task name. Thoughts?

![image](https://user-images.githubusercontent.com/5972966/112683972-afb19980-8e72-11eb-96dd-f51f17c90dbf.png)

**Comment by mathisdt** [comment]
I like the idea, it would provide a better overview. Tasks of type OUT don't have a task if I remember correctly, but the tasks only in the IN lines still would help.
