### ISSUE TITLE
Weird edit event delete animation

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#155]
![untitled](https://user-images.githubusercontent.com/5972966/113490030-fd0fb580-94c7-11eb-8a50-a4bf85d80d9c.gif)

Git head: 45cb7a88ce90c89d7e8a2c9c11aac035107e1244

**Comment by mathisdt** [comment]
You're right, this looks weird. It could be that I caused this by f7e96f9, I don't know...

**Comment by WildOrangutan** [comment]
That must be it, thanks 👍. Refreshing whole adapter is not ideal tough. Anyway, looks like just implementation of item id in adapter is wrong.
