### ISSUE TITLE
Edit event task name

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#157]
I find it conflicting, that "edit event" screen shows task name, but it actually doesn't save it.

[image](https://user-images.githubusercontent.com/5972966/113492386-487d9000-94d7-11eb-9e2f-4cc23a9d6e11.png)

Git head: 45cb7a88ce90c89d7e8a2c9c11aac035107e1244

**Comment by mathisdt** [comment]
One possibility would be to hide the task dropdown field (and its label) when the type of the edited event is set to "out". It would have to be displayed again when the type is changed to "in".
