### ISSUE TITLE
Digital time summaries

### ISSUE THREAD

**Issue by MrStephenGK** [mathisdt/trackworktime#169]
Hi,
Great app. Have been using it for a couple of years.
Would be great if the digital time of each day and for the week, could be displayed/available. This would be great as I manually complete a paper time sheet.

For example, for a day total of 4:30 (hh:mm) display 4.5 hours. Calculation done by dividing remanding minutes by 60, with variable rounding 1,2 digits
30/60 = .5
Therefore total day time in digital format would be 4.5

Cheers

**Comment by mathisdt** [comment]
This is going to be part of release 1.1.13. Thanks for the suggestion!
