### ISSUE TITLE
Request: View reports in-app

### ISSUE THREAD

**Issue by leoauri** [mathisdt/trackworktime#17]
Hi

I'd like to see the results of the reports in the app before exporting it.  Mostly I don't need to share the report with another app, I just want to see the information quickly.

Thanks

**Comment by leoauri** [comment]
What I really need to see is how much I spent working on a task in a particular time period, and I need to be able to fine tune the time period pretty precisely, i.e. how much I worked since a particular date (when I last billed or something).

At the moment I can only get reports which list clock in/out times, unless I'm missing something.
How do _you_ parse the data usefully?  You import this output into some other software?

**Comment by leoauri** [comment]
Another suggestion would be that the data can be exported as a csv list of _durations_, so they can be imported into a spreadsheet, sorted, added, and so on.  Currently the export is a list of in and out times which is difficult to use.  Actually just having start and finish times on one line of values would help

**Comment by mathisdt** [comment]
Thank you for your ideas! As to your question: I don't have to parse the data in detail, I only need monthly and yearly sums, but I see that this is not enough for everybody.

**Comment by leoauri** [comment]
I would try to implement the last suggestion, because I think I could just work that out.  I have pretty minimal experience with this kind of thing though.  Would you mind if I ask you some questions along the way?  Or what do you suggest?

**Comment by mathisdt** [comment]
I just sent you an email.

**Comment by WildOrangutan** [comment]
I would need smth like this. Can I simply make it as a preview screen, before exporting [like so](https://user-images.githubusercontent.com/5972966/115067863-c5563400-9ef1-11eb-9630-2ae8626c16bf.png)? Basically feed plain csv export string to TextView.

**Comment by mathisdt** [comment]
@WildOrangutan That would be welcome! If you like, you also may format it as a table instead of just continuous text, so the columns are visible better (for me, the table doesn't need any lines, formatting the values as columns would be enough).

**Comment by mathisdt** [comment]
A preview for reports was implemented in the meantime. I just forgot to close this issue.
