### ISSUE TITLE
Widget clock in no task

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#174]
If you clock-in with widget, task is not saved. I would presume, that it should save default task.

Version: 1.1.10-SNAPSHOT

**Comment by WildOrangutan** [comment]
@mathisdt I may have to change some stuff around `ThirdPartyReceiver`. Would it be okay, if I also change it to use default task for clock-in intents, that are received from other apps, in case no task is set?

**Comment by mathisdt** [comment]
Of course, that's fine by me. Sounds consistent.
