### ISSUE TITLE
Restore of Targets Backup not working without hints

### ISSUE THREAD

**Issue by jdckr** [mathisdt/trackworktime#178]
Hi,

restoring the backup of targets is not working if hints are not used.
In this case the check for number of columns fails as `line.split()` only returns 3 elements.
https://github.com/mathisdt/trackworktime/blob/5b697e3188f93619545f6a80a38a54b6a9c1c1a5/app/src/main/java/org/zephyrsoft/trackworktime/database/DAO.java#L991-L994

**Comment by mathisdt** [comment]
Thanks for noticing and speaking up! You're right, the `split` method used there (with one parameter) removes empty results from the end. I just tried the two-parameter `split` method and used `-1` as second parameter, which works fine. While at it, I'll introduce a precompiled pattern. The changes should be in the next release.
