### ISSUE TITLE
Request: report for all times

### ISSUE THREAD

**Issue by leoauri** [mathisdt/trackworktime#18]
At the moment reports exist for current and last time frames, but the most useful kind of report for me would be all times for one task.

Cheers

**Comment by mathisdt** [comment]
There is now a report containing all available data. If you only need the times for one specific task, you can generate the report "times by task" and then use only the one row you want.

This feature is not rolled out via Play Store or F-Droid yet, but I plan to publish an update of the app in the next few weeks.

**Comment by leoauri** [comment]
wonderful, nice to hear!

**Comment by mathisdt** [comment]
@leoauri The update is now live on Google Play. F-Droid follows.
