### ISSUE TITLE
Participate in hacktoberfest?

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#182]
Hey, I'm just wondering if you would like to participate in hacktoberfest. I use your app on daily basis and would prefer to spend some time on your app, during this event.

**Comment by mathisdt** [comment]
Thanks for the reminder! I think I removed the tag "hacktoberfest" last year, now I added it again. Pull requests welcome, especially on these issues (but others are also fine): #181 #180 #150 #100
