### ISSUE TITLE
Flexi time calculation wrong?

### ISSUE THREAD

**Issue by TFA-N** [mathisdt/trackworktime#188]
My Flexi time target is set to `20:00`. So for the week in the screenshot I would expect a flexi time account of 05:58, but it shows only 03:58. Am I misunderstanding the feature or is this a bug in calculation?
If that matters: It's the first week I started using this app, so every week before is at -20:00. For the following weeks, calculation seems to be working.

![image](https://user-images.githubusercontent.com/64919956/142447342-a76ea24d-5353-4174-86a9-bd62455f840a.png)

While I'm at it, I'd like to thank you for this fantastic app! I've been using it to track my student intern job for a while and it's great.

**Comment by mathisdt** [comment]
Thanks for taking the time to report this issue! If I see that correct (as you said this was the first week you used the app):
- On Monday, the expected working time seems to be 6 hours (starting at 0:00 flexi, worked 6:38, ended at 0:38 flexi).
- On Tuesday, the expected working time seems to be 4 hours (starting at 0:38 flexi, worked 5:55, ended at 2:33 flexi).
- Same on Wednesday, Thursday and Friday (4 expected hours each).

Either the calculation is wrong, or you provided a flexi start value of +2 hours in the settings - in the latter case you wouldn't have started at 0:00 flexi but at 2:00 flexi which then would make sense of it all. Could you have a look if that could be the cause of the discrepancy?

**Comment by TFA-N** [comment]
Thanks for your response! I checked and my start time is 00:00. In the previous empty weeks, the app correctly calculated 4 hours per day, which means on that Monday flexi time should have been 2:38. It seems to use 4 hours for every other day this week too, just not for Monday somehow. 

On 19 November 2021 08:33:08 CET, Mathis Dirksen-Thedens ***@***.***> wrote:
>Thanks for taking the time to report this issue! If I see that correct (as you said this was the first week you used the app):
>- On Monday, the expected working time seems to be 6 hours (starting at 0:00 flexi, worked 6:38, ended at 0:38 flexi).
>- On Tuesday, the expected working time seems to be 4 hours (starting at 0:38 flexi, worked 5:55, ended at 2:33 flexi).
>- Same on Wednesday, Thursday and Friday (4 expected hours each).
>
>Either the calculation is wrong, or you provided a flexi start value of +2 hours in the settings - in the latter case you wouldn't have started at 0:00 flexi but at 2:00 flexi which then would make sense of it all. Could you have a look if that could be the cause of the discrepancy?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mathisdt/trackworktime/issues/188#issuecomment-973825682
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mathisdt** [comment]
One other possibility remains: You can also set the target time for one single day different from the normal target time by tapping on the **date to the left the line**. The "Edit Target" screen appears, and if you have set the type to "Change target time" and entered 6:00 below, the situation you described would be the result.

**Comment by TFA-N** [comment]
Well this is embarrassing, there was indeed a different goal time for this day. I must have done that accidentally back then. Thank you very much for your patient explanation and help! 

On 19 November 2021 08:51:03 CET, Mathis Dirksen-Thedens ***@***.***> wrote:
>One other possibility remains: You can also set the target time for one single day different from the normal target time by tapping on the **date to the left the line**. The "Edit Target" screen appears, and if you have set the type to "Change target time" and entered 6:00 below, the situation you described would be the result.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mathisdt/trackworktime/issues/188#issuecomment-973838336
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
