### ISSUE TITLE
Detect Android’s work profile

### ISSUE THREAD

**Issue by nomeata** [mathisdt/trackworktime#203]
TIL about android’s [work profile](https://developer.android.com/work/managed-profiles) feature, which my company is using: Work apps are separated from non-work apps, and I can pause the work apps explicitly via the fast settings.

It seems that this would be a great way to also toggle the work time tracker: Work apps enabled – clocked in; work apps disabled – clocked out.

I don’t know if there is a way for Track Work Time to notice these events, though…

**Comment by mathisdt** [comment]
@nomeata I didn't look into work profiles yet, but if you only want an easy way to clock in and out from the quick settings, I have good news: this is already possible. Beginning with version 1.1.13, TWT has a custom tile which you can drag to the top and then use like any other tile - just tap on it to toggle your clocked-in status. The tile is highlighted while you're clocked in.

**Comment by nomeata** [comment]
Right, I am just looking for further tweaks :-)

But maybe better this way, I might be working while muting the work apps (or vise versa).

**Comment by mathisdt** [comment]
Given the Android API as it is, this seems impossible to me, so I'll close this issue. If someone finds out how to implement this, please comment and re-open!
