### ISSUE TITLE
Customize filename of reports

### ISSUE THREAD

**Issue by iceaway** [mathisdt/trackworktime#206]
When I enter my time reports in the time reporting tool my company has, I use the reports function to get a nice per-task overview. I usually keep these reports for future reference, but I have to rename them manually since the generated file name is fixed. It would be nice if it was possible to either use a template to create a custom filename, or to use something in the filename that identifies for example the year and week number (I have a vague memory that it used to be like this at some point in the past?).

**Comment by mathisdt** [comment]
The selected range will not be described in the filename as selected ("last week") but with the real dates ("from 2022-09-12 to 2022-09-18").

Sadly the Play store review process seems kind of stuck, version 1.1.17 is in review for about a week now and still not accepted by Google (but also not denied), so I don't know when this feature will land...

**Comment by iceaway** [comment]
This is great news! Thank you @mathisdt!
