### ISSUE TITLE
Allow adding past events (which you missed past week)

### ISSUE THREAD

**Issue by HMT-HRO-MaMe** [mathisdt/trackworktime#211]
Hi, I have an issue that might affect also others and don't see any workaround.

If you missed to add e.g. a stop event last week, you are unable to fix it because the UI only allows you to pick current / future dates. While I see, that this is the usual usecase and might prevent you from cheating, this also blocks you to fix things.

For example at friday I missed to add the end and TWT will take the following days into account (not sure if seperated bug?). All I needed to do is to add a end event to Friday, but the UI prevents me to do so 😕 
![TWT - Reust fixing past days](https://user-images.githubusercontent.com/102375018/178523822-00a5adf1-e6ec-46f7-96e5-47ee808b6106.png)

**Comment by mathisdt** [comment]
Hi and thanks for your reports! This one is really just a mishap of me designing a UI - you can swipe left and right on the table and then get to the next/previous week. If you tap on the table, you can edit the events of the currently displayed week - so you just have to switch to the week you want to fix times _previously to tapping on the table_, and then you are able to.

In the settings you can also enable buttons above the table, maybe they would make it a bit more obvious, but they're hidden by default.

This should help you editing events from other weeks. If there's still a problem, you're welcome to comment here again and/or reopen this issue!

**Comment by mathisdt** [comment]
As far as I can see from your screenshot, the date picker is limited to **last week** here (July 4th to 10th). This should be the case when you swiped into last week before editing the events. This is on purpose - I don't want to put my events into the wrong week by accident, so I go to the week I want to edit and then edit the events for that week. When I'm done there, I go to another week and edit the events for that week.

**Comment by HMT-HRO-MaMe** [comment]
Sorry  I didn't noticed that it will switch if you move to the last week before. I used the full overview.
