### ISSUE TITLE
Notification re-appearing constantly

### ISSUE THREAD

**Issue by Lucas-Sichardt** [mathisdt/trackworktime#212]
Hi and thanks for your app!

I'm using it to track my working time when being in on-call duties.
For this I use the app "Automation" to detect incoming calls (and their end) from work and send a broadcast to Track Work Time. It also mointors my position to send a broadcast to Track Work Time when I enter the working place.

To prevent these automatisms from being triggered in my free time (e. g. when passing the working place building on a walk) I use the notification option of Track Work Time when being clocked-in, for which Automation ckecks before sending the broadcasts.

Unfortunately the notification seems to be recreated every now and then which triggers the Automation rules and leads to another broadcast to be sent. 
So - for example - if I'm already checked-in being at work and the notification gets recreated I end up with another check-in entry in Track Work Time.

I'm sure, the notification is recreated every time when activating the Track Work Time app in foreground. But additionally it happens some kind of randomly too. Sometimes I get just double entries in Track Work Time but I also had a case with about 50 duplicates in two minutes during an incoming call while driving (so there was a call and Android Auto was running).
But it also happens when the phone is not used - just randomly.

Would be great if this problem could br changed.
It seems to be related to these:
https://github.com/mathisdt/trackworktime/issues/45
and
https://github.com/mathisdt/trackworktime/issues/60

Thanks!

Lucas

**Comment by mathisdt** [comment]
There is an option now which removes the details from the persistent notification so no frequent updates are necessary. If this option is enabled, the notification won't get updated while clocked in. The feature will be in the next released version.

**Comment by Lucas-Sichardt** [comment]
Sounds great, thank you!
-- 
Lucas Sichardt
***@***.***
http://lucas.sichardt.net

(Diese E-Mail habe ich von einem Mobiltelefon aus geschickt; eine eventuell erhöhte Häufigkeit von dadurch bedingten Tippfehlern bitte ich zu entschuldigen.)

Am 27. Juli 2022 22:03:53 MESZ schrieb Mathis Dirksen-Thedens ***@***.***>:
