### ISSUE TITLE
[Feature Request] Track driven miles for specific tasks

### ISSUE THREAD

**Issue by DamourJustin** [mathisdt/trackworktime#216]
Hi, 

I understand this may be out of scope for the project (if it is feel free to close this), but I think a simple for of mileage tracking would go hand and hand with time tracking. It is a feature that would at least help me out a lot so I don't have to keep track of it outside of the app.

I think it would be great if, when you created a task, you could select an option to track miles as well as time. Then, when you clock out of a task it would ask you how many miles/km you drove. Then on your report it would be great if you could see miles per task. A simple implementation such as that may be enough for some use cases. You could get more advanced with odometer tracking or actually using GPS to track, but that may not be necessary.

I'd be curious if the people working on this project were interested in this feature, and if so, how they would want it implemented!

**Comment by mathisdt** [comment]
This could be implemented by adding the reverse of what's already there: messages ("intents") which other apps can send to TWT and start or stop time tracking. But this reversed would mean that TWT sends intents when events occur (clock-in / clock-out) and another app could react on them by starting or stopping a GPS tracking in the background.

For this to work, the generated intents should bear the event time and type (obviously) but also the task. By using different tasks for "track me via GPS" and "don't track me" the user can decide inside TWT if the tracking should be used or not.

Examples for apps which could receive those intents:
- Automate ([Play Store](https://play.google.com/store/apps/details?id=com.llamalab.automate))
- Automation ([F-Droid](https://f-droid.org/de/packages/com.jens.automation2/) / [Play Store](https://play.google.com/store/apps/details?id=com.jens.automation2))

**Comment by mathisdt** [comment]
Broadcast intents will come in release 1.1.18. With that in place, you should be able to build your mileage tracking setup using an automation app of your choice, probably even using GPS. See #217 for more details on available actions and extras, and the [README](https://github.com/mathisdt/trackworktime/blob/master/README.md) also has new paragraph on that.
