### ISSUE TITLE
twt seems to have lost all my data

### ISSUE THREAD

**Issue by macxcool** [mathisdt/trackworktime#228]
I opened twt this evening and it asked me to tell it where to store backups. No matter what I did, there was no data, even though I use it daily. There is no data for last week, for instance, and there should be time for just about every day.
I'm not sure what to do.

**Comment by macxcool** [comment]
Where does twt store its data, normally, anyway? I've never been able to find it.

**Comment by mathisdt** [comment]
I have to ask some questions to understand better what happened and how to proceed.

- Does the app still show your data from last week? If not, what did you do/configure besides selecting a backup directory?
- Did you select a directory for TWT to store the backups in, or did you cancel the process?
- Did you re-install TWT from a different source? There are three: Google Play Store, F-Droid and APK files from Github. Play Store and APK files have the same signatures, but F-Droid creates the package on its own and also applies its own signature. Android does not allow an app to continue using the same database when it's reinstalled with a different signature, so maybe this is why the data is gone.
- Could you send me the log file via email? There's a button for that in the menu. I hope to gain additional information from it and then could contact you via email reply which seems more appropriate in this case.

TWT stores its data in Android's built-in SQlite database which every app can use for its data. If you trust Google, you can enable backup to Google's servers in the settings, but if not, the on-device backup directory should provide means to synchronize the backup via a custom solution, e.g. [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite). Once a day, TWT dumps all data is has (settings and events) into the directory, ready for your backup mechanism to pick it up.

**Comment by macxcool** [comment]
See below \/
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Nov 29, 2022, 2:21 PM by ***@***.***:

>
>
>
>
> I have to ask some questions to understand better what happened and how to proceed.
>
> Does the app still show your data from last week? If not, what did you do/configure besides selecting a backup directory?
>
I just selected a backup directory. The same one that was selected before.
> Did you select a directory for TWT to store the backups in, or did you cancel the process?
>
I cancelled at first, but then stupidly ran it again and selected the backup folder.
> Did you re-install TWT from a different source? There are three: Google Play Store, F-Droid and APK files from Github. Play Store and APK files have the same signatures, but F-Droid creates the package on its own and also applies its own signature. Android does not allow an app to continue using the same database when it's reinstalled with a different signature, so maybe this is why the data is gone.
>
No. I haven't installed at all since the last update.
> Could you send me the log file via email? There's a button for that in the menu. I hope to gain additional information from it and then could contact you via email reply which seems more appropriate in this case.
>
I will. I think I messed up really badly in response to the 'Select a backup dir.' message. I tried restoring from a previous backup once I saw that my data was gone, but it only had data up to the middle of October, which doesn't help me at all.
>
> TWT stores its data in Android's built-in SQlite database which every app can use for its data. If you trust Google, you can enable backup to Google's servers in the settings, but if not, the on-device backup directory should provide means to synchronize the backup via a custom solution, e.g. > FolderSync <https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite>> . Once a day, TWT dumps all data is has (settings and events) into the directory, ready for your backup mechanism to pick it up.
>
>
The big problem with the Google backup is that there doesn't seem to be any way of accessing the files without doing a complete restore to a new Android device. I tried this with Androidx86 in VirtualBox, but no luck.
I do use PCloud, but the mobile app is limited in the way I can configure it to backup certain folders.

**Comment by mathisdt** [comment]
It seems that an old backup was used to restore from. This overwrote the app's newer data.

To prevent such problems in the future, the app should display the backup's time range before restoring it (see #229).
