### ISSUE TITLE
problem when changing backup target directory

### ISSUE THREAD

**Issue by mar565** [mathisdt/trackworktime#246]
I cant set up a local folder and I think there is an issue with how the app asks for storage access. Selecting the folder doesnt do anything beside requesting access again.
The option for storage access isnt available in the apps settings as shown in the Screenshot.

![Screenshot_20230618-161744](https://github.com/mathisdt/trackworktime/assets/49168222/8a6981fb-4a24-4f01-ac48-d8c28f39c3e7)

**Comment by mathisdt** [comment]
Firstly, please make sure you have the latest version of the app (1.1.20). Then, if that is given, what is shown when you tap on the last entry in the menu (labeled "Select Data Directory")? Normally this should give a hint which directory is currently selected. (It's normal that the system permissions don't show anything storage-related, the app uses the old way of accessing the device storage.) Finally, if the app keeps asking for the directory, please send the logs to me *on the same day as the error(s) occurred*. (This is important, the "Send Logs" feature only sends the log file of the current day.) You also can send the logs to yourself first and redact anything you don't want to share, that's completely OK.

**Comment by mathisdt** [comment]
@mar565 Did you find out anything conclusive? I also use the latest GrapheneOS and have the same app permissions (no storage visible), but it works - the app happily writes its backups every day.

**Comment by mathisdt** [comment]
Thanks for the bug report! I was able to identify the problem: When I first implemented the directory selection, I saved the target location in the running app. So it wasn't read again until after a complete app restart and effectively unchanged. Now the new backup target is used immediately after selecting it.
