### ISSUE TITLE
jalali calendar

### ISSUE THREAD

**Issue by mohammadZahedian** [mathisdt/trackworktime#260]
is it possible to add jalali calendar?

**Comment by mathisdt** [comment]
No, but that's nothing against the Jalali calendar - it's impossible to add **any** calendar. Currently, the app only can be used for time tracking in a week beginning on Monday - there's a [ticket](https://github.com/mathisdt/trackworktime/issues/34) to add the possibility to also start on any other (configurable) day of the week, but that's all. No calendar involved whatsoever.
