### ISSUE TITLE
Location based tracking does not work

### ISSUE THREAD

**Issue by berceanu** [mathisdt/trackworktime#27]
Using `Android 8.0.0` on my `OnePlus 3` phone, I have enabled `Track by location`, entered the latitude and longitude with a precision of 20 meters from the GPS, put a tolerance of 500 meters, and the tracking does no start automatically when I get to work. My home is about 2 km away so it should detect a change I think.

**Comment by mathisdt** [comment]
The mechanism for tracking by location works with cell coordinates and uses no GPS even if available because that would drain the battery really fast. If your phone company only has one base station covering the whole area, the location can be really inaccurate (some stations in Germany only provide a location with 2.5 km tolerance).

Did you try the menu item "Here = Work" ([screenshot](https://user-images.githubusercontent.com/1932462/34849725-b80d0dc4-f723-11e7-9df4-f30c605e3427.png))? By using it, TWT uses the current location as provided by the base station(s) in reach as work location - perhaps that helps.

**Comment by berceanu** [comment]
Perhaps checking GPS once every 30 mins or so would not drain the battery so much?
It might indeed be the case that there is only one cell tower in the region. One way that occurs to me for checking that is to tap `Here = Work` at my workplace and home and compare the results.

But ultimately I would like to find a way to rely on the GPS for this since the precision is much better. Perhaps by using `Llama`/`Tasker`?

**Comment by berceanu** [comment]
Perhaps checking GPS once every 30 mins or so would not drain the battery so much?
It might indeed be the case that there is only one cell tower in the region. One way that occurs to me for checking that is to tap `Here = Work` at my workplace and home and compare the results.

But ultimately I would like to find a way to rely on the GPS for this since the precision is much better. Perhaps by using `Llama`/`Tasker`? Are you aware of any other apps that do this?

**Comment by mathisdt** [comment]
My goal for writing TWT was to clock in and out by the minute so checking for GPS position every 30 minutes would not help (although the battery consumption would be considerably lower than checking for GPS position every minute, you're right).

I don't use general automation apps at the moment, but I'm sure [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm), [Llama](https://play.google.com/store/apps/details?id=com.kebab.Llama) or [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) could help. All the app has to do is to create intents as described [here](https://zephyrsoft.org/trackworktime) (or in the README).

Could you report the result when you tried `Here = Work` at both your workplace and home? I'd like to know if that's really the problem. You don't have to give the exact values, anonymized values are fine - the difference is interesting. 😄

**Comment by berceanu** [comment]
OK so I did that. First strange thing is that `Tolerance`, both at home and work is 2000. The latitude is exactly the same in the two locations, and the longitude has a difference of 0.025202. 

I installed `Automate` but can't figure out how to configure it to send the clock-in and clock-out broadcast intents.

**Comment by mathisdt** [comment]
Depending on where you are located, a difference of 0.025202 in longitude is 2.8 kilometers at maximum (along the equator). Given the tolerance your cell tower combination is only able to provide, it is possible that the app still sees your phone in the same (rough) location and therefore does not clock you in.

Regarding Automate, the information at https://llamalab.com/automate/doc/block/activity_start.html could help. But did you try Llama and Tasker? Those apps are known to work with TWT.

**Comment by berceanu** [comment]
Llama also uses phone masts iirc..
