### ISSUE TITLE
[bug] location is scanned on unchecked days.

### ISSUE THREAD

**Issue by carnager** [mathisdt/trackworktime#273]
If one has defined work days in options Dialog, the app shouldn't scan for location on unchecked days, right now it seems to do just that.

**Comment by mathisdt** [comment]
This behaviour is actually wanted. The "working days" configured in the options only are for distributing the planned weekly work time evenly and not for excluding the other days - people sometimes work on weekends (which they don't do normally) and this time also should be counted.

There could be an extra option to switch off automatic tracking (for both mobile network location and WiFi) on days not configured as working days, but that would be a feature request.
