### ISSUE TITLE
Question about "Backup to Google Servers"

### ISSUE THREAD

**Issue by RedCommander735** [mathisdt/trackworktime#281]
I set the option to true, but I don't really understand where the backup is going and it also never made any.

**Comment by mathisdt** [comment]
Hi!

In short, the "Backup to Google Servers" feature saves a copy of the app's data in your Google account. If you switch devices and install TWT on your new device, the app data should be restored as if you manually copied a file-based backup there and restored it (from the menu of the app).

But I can't really tell if it still works, the code was contributed for an older Android version, and I never used it as I don't trust Google with my personal data.

**In my opinion, the file-based backup is a much more robust way of keeping your data safe** ([here's a short description](https://zephyrsoft.org/trackworktime/faq/#how-can-i-create-a-backup-maybe-for-a-restore-on-another-device)).

**Comment by RedCommander735** [comment]
I don't really think that it works any more, since normally when something wants to access Google Drive it has to ask permission, and that wasn't the case here. Thank you for the answer though, I'll try the file-based backup
