### ISSUE TITLE
Often writes to twt_automatic_backup files when not used

### ISSUE THREAD

**Issue by Catfriend1** [mathisdt/trackworktime#282]
Hi,

Thanks for the companion I use since years :). I am  on the latest fdroid release on Android 14. But this also occurered on older Android versions as well. 

When I do not use the app, it writes every X minutes to the backup files. I would suggest it should not do this when I am not clocked in = no notification of TWT is present as data does not change when the app is unused. Maybe this also saves some battery then, because the phone cpu has to wake to do the backup of unchanged event data.

Thanks.

Regards,
Catfriend1

**Comment by mathisdt** [comment]
Thanks for your report! Unfortunately I can't reproduce the issue, on my devices and simulators the backup files are only written once a day (as it should be). Could you send me your log file (maybe after redacting it for your privacy)? [Here](https://zephyrsoft.org/trackworktime/faq/#how-can-i-send-the-logs-to-the-developer)'s how that works.

**Comment by Catfriend1** [comment]
Hmm indeed, today it only backed up at 09.58, yesterday was 8.40. i'll observe...
