### ISSUE TITLE
Can't retrive twtdata from intent with Tasker

### ISSUE THREAD

**Issue by CarloHD** [mathisdt/trackworktime#310]
idk if is my misconfiguration of Tasker action or a Tasker bug, or if is a bug on TWT, so I chose to start asking here.

---

following [these guidelines](https://zephyrsoft.org/trackworktime/), i've configure the intent sender in that way:

<img src="https://github.com/user-attachments/assets/e5bd31b4-a065-4f3c-9424-ef6bc6e7bf38" width="300" >

and the listener:
<img src="https://github.com/user-attachments/assets/de0c3ba8-5e8b-40e9-aff0-d05efd33f360" width="300" >

according to [Tasker guide](https://tasker.joaoapps.com/userguide/en/intents.html)

> Accessing Intent Data
>When an intent triggers an Intent Received event, the resulting task(s) which are executed have access to many details of the intent via local variables (where relevant and present):
>
> - %intent_data: the data
> - %evtprm1: the action
> - %evtprm2: the first category
> - %evtprm3: the second category
> - %evtprm4: the URI scheme
> - %evtprm5: the MIME type 
>
> In addition, any extras attached to the intent can be accessed under their name, with the following modifications to make them valid variable names:
>
> - all letters will be converted to lower-case, then
> - names of length less than 3 will have var_ prefixed
> - non-letter-or-digit characters will be converted to _, then
> -  names not starting with a letter will have a prefixed, then
> - names not ending with a letter or digit will have a affixed
> - if the result is the name of another extra, _dup will be affixed until that is no longer the case 

--- 

So, i can't understand where to set "twtdata" , because on TWT guidelines it was setted on "Dictionary with broadcast extras", an input presenst in Automate, but on Tasker there's any similiar input on Received Intent settings.

I've tried to read "%intent_data", but it's an empty variable, i've tried to set on extra on the intent sender "intent_data:twtdata" or simply "twtdata", but nothing...

I can't figure out how to receive/read the intent data. What am i missing??

**Comment by mathisdt** [comment]
Hi Carlo! I don't have Tasker (and won't buy it), so my ability to help will be limited, but I have some observations/ideas:
- The extra line containing "twtdata" in the "Send Intent" screen can be left out. The term "twtdata" is only used for Automate to put the received data somewhere - this "somewhere" is called "twtdata" so the following action can read the data. I don't know how Tasker does this.
- To check if tasker sends an intent which actually reaches TWT, you can inspect the log of TWT. To do that, trigger the sending of the intent in Tasker and directly afterwards go to TWT, select "Send Logs" from the menu and send the log to **yourself** (more information at https://zephyrsoft.org/trackworktime/faq/#how-can-i-send-the-logs-to-the-developer). Then look for "ThirdPartyReceiver.onReceive" in the log file, this line should tell you what TWT answered (and when). If there's no such line, the intent didn't reach TWT.
- Perhaps first try sending an intent from Tasker to Tasker (without TWT in the middle). After figuring out how to do that, it should be easier to address TWT.

Hope this helps a little.

**Comment by CarloHD** [comment]
i've follow your advice to read the log and it was perfect!

After sending StatusRequest Intent, depending on witch state i am i've got these logs:

- When no TWT Task was started
`DEBUG ThirdPartyReceiver.onReceive - sending status reply: status-request Bundle[{status=clocked-out, minutes-remaining=null}]`

- After a TWT Task was started
` DEBUG ThirdPartyReceiver.onReceive - sending status reply: status-request Bundle[{current-task-name=Default, status=clocked-in, minutes-remaining=null, current-task-id=1}]`

on Tasker i can access directly to that value by using %status for example, or %current_task_name 
_(NOTE Tasker guideline: non-letter-or-digit characters will be converted to "\_" )_ 

the variables with "null" hasn't any vaule, not a "null" string

Maybe you can use that information for update the main page 

Thks @mathisdt

**Comment by mathisdt** [comment]
Thanks, I updated the TWT overview page and also inserted a link to this issue.
