### ISSUE TITLE
correct "Worked Total"

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#39]
The "Worked Total" is incorrect sometimes, see [screenshot](https://user-images.githubusercontent.com/1932462/41196058-c181ca18-6c38-11e8-892f-924548fc0bbd.png).

**Comment by worraps** [comment]
Additional Screenshots... still a problem (works some times)  Try to manually edit times, but calc total won't change...

![Screenshot_2020-02-11-17-45-59](https://user-images.githubusercontent.com/1423504/74290128-e96f2180-4cfe-11ea-85d3-8856d5be3958.png)
![Screenshot_2020-02-11-17-45-52](https://user-images.githubusercontent.com/1423504/74290129-ea07b800-4cfe-11ea-8452-ff22ecc304f7.png)

**Comment by worraps** [comment]
My issue was identified... two weeks earlier, I had an open **in** time without an end time.  Even though the summary screen adds the 23:59 for local calculation, it does not carry that over to future weeks so the next active day assumed a startime of 00:00 even though another starttime was entered (ignoring my 19:29 start time in screenshot)
