### ISSUE TITLE
Overview by day/week of time sums by task

### ISSUE THREAD

**Issue by DuncanLithgow** [mathisdt/trackworktime#46]
This may not be a bug (unless not being able to find something is a bug) but there's something I can't find.

How do I find how much I've worked on each task summed for the day and week in app? 

Case 1: I get to work on monday and have to fill out my time sheet adding the totals for each project for each day. Where do I go to see a days tasks and sums?
Case 2: I need to see if i correctly logged the time I spent earlier in the week on a certain project. I think I forgot to log the hour I spent reading a report on the train. Where do I go to see a days tasks and sums and make those changes?
Case 3: I logged 3 hours of admin today. On second thoughts I should have logged half of it to a specific project. Where do I go to see a days tasks and sums and make those changes?

The picture is of the in app report from ATimeTracker (which I am looking to migrate from because this report is also very tricky to use as a reference for making changes and correction.)
![screenshot_20181015-094834](https://user-images.githubusercontent.com/3223028/46936802-d9d6be80-d05f-11e8-9629-438a69a3fd97.jpg)

**Comment by mathisdt** [comment]
Currently there is no report for the tracked time per task and day - only per task and week (or month), and reports are generally CSV files so reading them on your mobile device requires another app capable of handling CSV files. 
If you have to see daily sums per task, you have to calculate it yourself (you can get a report with all events and do the math in a spreadsheet). There is also the possibility to tap onto the week table and see all events. But having read your requirements, I think this app is not really that useful to you. 

If you want TWT to add features, please write new issues describing the features, but there's no guarantee the features will be implemented anytime soon!
