### ISSUE TITLE
Add translations support

### ISSUE THREAD

**Issue by drizt** [mathisdt/trackworktime#57]
I want to add Russian translation but don't see how it can be done.

**Comment by WildOrangutan** [comment]
Should be pretty straight forward, by adding `values-ru/strings.xml` definitions. Check android guide for more info: https://developer.android.com/training/basics/supporting-devices/languages

**Comment by drizt** [comment]
Thanks will see.

**Comment by mathisdt** [comment]
I'm looking forward to see a pull request from you, @drizt! :blush:
