### ISSUE TITLE
How to open report?

### ISSUE THREAD

**Issue by drizt** [mathisdt/trackworktime#58]
I tap on Tasks in menu but see only Send report window. I can't find how to open report on phone.

**Comment by mathisdt** [comment]
You can only export data as CSV file, Track Work Time doesn't have in-app reports.

I propose you install a spreadsheet processing app on your phone, create a report as CSV file and open it in the other app. You can use the "Share" menu which is opened after creating a report.

**Comment by mathisdt** [comment]
Sorry, I think I misunderstood you - did the app crash and you saw the window to send an error report to me?

**Comment by drizt** [comment]
I mean I want to know how many time I spend for a task. TWT shows only total time on main display. So to get individual times I tap menu -> Reports -> TIMES BY TASK. See screenshots.

![1](https://user-images.githubusercontent.com/534665/59372611-5772db80-8d61-11e9-9b7e-42e738ccc216.png)
![2](https://user-images.githubusercontent.com/534665/59372630-6063ad00-8d61-11e9-87fd-68380f800e3e.png)
![3](https://user-images.githubusercontent.com/534665/59372643-65286100-8d61-11e9-84c5-dd4c809c0e45.png)

**Comment by mathisdt** [comment]
In this case, I'm afraid you have to install a spreadsheet processing app on your phone, create a report as CSV file and open it in the other app (as I stated in my first response). TWT doesn't support viewing reports in the app itself, reports are only exportable.

Alternatively, you can email the report to yourself and open the CSV file on your computer using LibreOffice or MS Excel.
