### ISSUE TITLE
Vibration notification fires randomly

### ISSUE THREAD

**Issue by lee-tts** [mathisdt/trackworktime#60]
Android 9 / LineageOS 16 / microg
App v. 1.0.5 from F-droid

Auto pause off
Flexi time off
'Check if you work on this day' all off
Location tracking off
Wifi based tracking off
Notification enabled only when clocked in

When I am clocked in, the app will vibrate every few seconds, sometimes every 10 seconds, sometimes 30 seconds or more. 

Is this normal? 

Thank you!

**Comment by mathisdt** [comment]
This seems to be a duplicate of (or at least related to) #45.

**Comment by lee-tts** [comment]
In a sense it's not a bad bug because it reminds me to stop tracking when I'm done working haha

**Comment by mathisdt** [comment]
Closed with PR #64.
