### ISSUE TITLE
Flexi time per day

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#66]
I think it would make more sense to have flexi column display flexi delta per day. Basically similarly to how work hours work. For example:

| day   | in | out | worked | flexi |
|-------|----|-----|--------|-------|
| Mo    |    |     | 8:00   | +0:30 |
| Tu    |    |     | 8:00   | +0:30 |
| Total |    |     | 16:00  | +1:00 |

Thoughts?

**Comment by mathisdt** [comment]
The concept of the flexi time column is to keep track of current over- or undertime. This wouldn't be possible when only the daily value was visible, so I'd opt for keeping the sum in the flexi column.

This does not mean the daily value can't be displayed, but I'd prefer it to be **additional** (in a new column) or **configurable** (if a preference is set, then the flexi column displays the daily value and not the sum anymore).

**Comment by WildOrangutan** [comment]
Hum... seems like I've misinterpreted how total flexi works. Rethinking this, current solution seems more appealing. Sorry.
