### ISSUE TITLE
Restructure report screen

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#67]
I think report screen started having too many buttons at this point. I suggest doing something like following left image (right for reference). 

Opinions?

![image](https://user-images.githubusercontent.com/5972966/66123358-12113d00-e5e2-11e9-8a58-d0bff3ba8d6a.png)

**Comment by mathisdt** [comment]
I like the left screen better.

**Comment by mathisdt** [comment]
Didn't you add "day" as option in the "range" section? It's not in the screenshot...

**Comment by WildOrangutan** [comment]
Ok, I'll go ahead and implement it then

**Comment by mathisdt** [comment]
closed by PR #69
