### ISSUE TITLE
fix remaining work time in notification

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#7]
When the options "use flexi time 0:00 as target" and "countdown to 0:00 every day" are enabled, the notification sometimes displays incorrect finishing times. Especially high overtime amounts (more than one working day) could be the cause of the miscalculation, it seems that the displayed "possible finishing time" is from some days back. In case the flexi time is more than the rest for today it should display "now".

Method `getFinishingTime` of class `TimerManager` is likely to be wrong.

**Comment by Heis** [comment]
I was wondering why it showed I could be done so early. I guess it assumes that you can take all your flextime on the current day and that is what it means by "countdown to 0:00 every day". I turned off "countdown to 0:00 every day", and the proposed end time is now correct and according to the set norm work week.
