### ISSUE TITLE
Flexi time off-days

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#70]
Would be nice to add option to exclude specific days from flexi time.

For example, when I go to vacation for a week, I get minus 40 h of flexi time. So to compensate for that, I have to manually offset it by adding +40 to "start value for flexi time". 

If I don't compensate for that, all future flexi values are offset.

I'm most annoyed with this, due to the fast I have to manually calculate new flexi offset value. Additionally it messes up clock in history.

**Comment by mathisdt** [comment]
@dirkmb implemented just this in PR #59, so I'll close this as duplicate (see issue #47).

The feature is on master branch, but not in a release yet. You have to add an event of type FLEX on each day you want to exclude, and it won't touch your flexi time sum for that day.

**Comment by mathisdt** [comment]
Just for the record: before #59 you already could handle a week of vacation as follows:
1. add a task for vacation
2. use the menu item "Multi-Insert" to clock the week using this task

Result: Your flexi time stays the same and you know exactly what you did during that week (which is not the case if you use FLEX events) - I even added a task for illness so I could also keep track of these unpleasant times.
