### ISSUE TITLE
Week swiping

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#71]
I think it would be handy to implement swiping on the main screen, so that you could swipe left and right between weeks and using scrolling tab layout. Something like [this](https://user-images.githubusercontent.com/5972966/66342843-a107b780-e94a-11e9-86e4-aaed176e0d1e.gif).

**Comment by mathisdt** [comment]
That would be really nice! :smiley: I had that in a very early version of the app (pre-1.0) but I found it very hard to maintain. Perhaps the current library support is better.

**Comment by WildOrangutan** [comment]
I've done similar stuff at work, and it's pretty simple to implement. Library does a lot of stuff for you. You just need to implement adapter for views and wire it together with `ViewPager` and `TabLayout`.

**Comment by WildOrangutan** [comment]
Gonna go ahead and try implementing it

**Comment by mathisdt** [comment]
:+1:

**Comment by WildOrangutan** [comment]
Just a bit of update, if there's something you may not like.

As you can see from referenced commit, I've started by moving week controlling logic to separate fragment, since I'll need to create multiple instances of week view. Fragment is not my preferred choice, but it keeps logic changing to a minimum.

My next step will be to try to modify it to work with fragment adapter. I intend to remove "previous" and "next" button, and change "today" button to show conditionally, when current week is not showing.

**Comment by WildOrangutan** [comment]
Ok, I'll use new view pager. 
One more question, do you think I should make separate PR for androidx migration?

**Comment by mathisdt** [comment]
A separate PR for the migration would be nice, Peter! Thank you for your effort! :smiley:
