### ISSUE TITLE
Remember report selection

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#72]
I think it would make sense to remember report selection and select it by default the next time.

For example, in my case, I most commonly use:  "last" + "month" + "all events". At most, sometimes change "last" to "current".

**Comment by WildOrangutan** [comment]
Going to implement this, since it's annoying me 😊

**Comment by mathisdt** [comment]
You're welcome (please keep in mind that #113 might cause conflicts).

**Comment by WildOrangutan** [comment]
Hm yeah, there will be conflicts, if I want to do this atm. I guess I can wait a bit more with this.
