### ISSUE TITLE
Feature request: adding events outside of current week

### ISSUE THREAD

**Issue by Skymirrh** [mathisdt/trackworktime#73]
Hello!

Love your app, thank you for your work :)

I have noticed it is not possible to add an event outside of current work week, whether it be before or after (blocked [here](https://github.com/mathisdt/trackworktime/blob/ab685b6652f6f8668b6540ec70550651a09e8f50/app/src/main/java/org/zephyrsoft/trackworktime/EventEditActivity.java#L295)).

Is there a specific reason this is not allowed? I sometimes record events at a later date, and sometimes I'm blocked because of this.

So far, the workaround I have been using is a multi-insert, which allows to add events in the past/future, followed by a manual edit.

However this workaround is not perfect as it does not work in one specific case: when I'm working on days I'm usually not. 

As an example: I usually work 5 days a week (Monday-Friday). From time to time, I am required to work on a Saturday or Sunday. If I am smart enough to log time before the week ends, all is good: I can add events on Saturday and Sunday even though they are not part of my regular work week. However if I forget to log on Saturday or Sunday, then on Monday I'm screwed because multi-insert will never insert times on days that are not regular work days ([blocked here](https://github.com/mathisdt/trackworktime/blob/8a733ebaa78e106282b004ce8266ae0c076c5c31/app/src/main/java/org/zephyrsoft/trackworktime/timer/TimerManager.java#L76)).

**Comment by mathisdt** [comment]
Hi @Skymirrh, thanks for your feedback!
The reason for this restriction was to prevent the user from mis-selecting a date outside of his current time range. Currently, you can use the buttons above the table to change the displayed week and then easily add an event by "normal" means (tap on the table to show the event list and add an event via the menu) - when #71 is done you will even be able to swipe the table right or left to change weeks.
If you still feel this restriction is too harsh, feel free to re-open this issue! :blush:

**Comment by Skymirrh** [comment]
Oh, I see how it works now! My bad, I should have guessed it should be possible to switch the current week when looking at the code.
