### ISSUE TITLE
help for "flex" event type

### ISSUE THREAD

**Issue by mathisdt** [mathisdt/trackworktime#78]
The title "flex time" for the recently added event type (see #47 and #70) can be slightly misleading because it has little to do with flex time itself. The event type makes the day not count for calculating flex time balance, so in essence it is a signal for a day off and should be called accordingly.

**Comment by mathisdt** [comment]
@dirkmb, are you OK with this? Or do you have a better idea to clarify the meaning of the new event type? Some people already asked me what "flex time" events would mean, so I think we have to name it better. I'm open to suggestions!

**Comment by dirkmb** [comment]
Oh sorry did not saw this issue.
If you insert a time other than 0:0 you also can set an individual flex time per day. So e.g. if you have to work on the first Sunday each Month you may want to enter a Flex-Time-Event at this day at 8:00 (assuming you have to work for 8 hours on this day).
So naming it 'day off' only makes sense if the time is always set to 0:0.
Another example for not using 0:0 would be if you have a half day off you may want to change the flex time to 4:0.

So 'day off' is a valid name only if the time is restricted to 0:0.

**Comment by mathisdt** [comment]
That restriction would take away some of the freedom the new event type brings, so I'd like to stay away from that. Do we have another option to inform the user better about it? Perhaps a preferably short info text or something like that? I can imagine users are not aware of the possibilities (or dangers, as some might put it).

**Comment by WildOrangutan** [comment]
Since it seems to work as flexi time target per specific day, I suggest renaming it to "flexi target". Tough I think another description is needed, both in case of "start/stop tracking" and "flex time" respectively.

When start/stop tracking is selected, it should say that you're modifying **events** and work duration will be determined between them.

In case of "flex time", I think it should say that you're changing/overriding flexi target **duration**.

**Comment by dirkmb** [comment]
"flexi target" sounds good for me.
And a explanation how it works would ne nice indeed. But I've no idea where to put it. On a Deskatop-Application I would place it in the tooltip of the radio button, but that does not work on Android-Apps.

**Comment by WildOrangutan** [comment]
I'd suggest something like [this](https://user-images.githubusercontent.com/5972966/69479079-bbfa9200-0df9-11ea-8818-f27566471bce.png).

Alternatively, one could maybe make some question mark image button, that shows [tooltip](https://developer.android.com/guide/topics/ui/tooltips).

**Comment by mathisdt** [comment]
@dirkmb Could you please verify that I correctly [described the function of flex events](https://github.com/mathisdt/trackworktime/commit/e14edf86400fbc6c24eb7ae65061d9832b12b40a#diff-01dafb3fd0217441330103cfc8300094R39)?

**Comment by dirkmb** [comment]
Yes I like it. I added one comment to the commit.

**Comment by mathisdt** [comment]
Thanks @dirkmb! I corrected the duplicate word.
