### ISSUE TITLE
Separate applicationId for development

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#82]
Would you be ok, if I change the app, so that both release and debug can be installed at the same time? This would require at least changing `applicationId` and `Constants.DATA_DIR`.

This would make it a bit easier to test the app on my phone, alongside release version from google play.

**Comment by mathisdt** [comment]
Could you do that on the development branch in your account without merging it back? Contrary to you, I'm fond of being able to test both appstore and development version with the same data on the same device, just by switching the APK. 

If you want, you can build a switch into the Gradle build which **manually** can cause the data to be altered, but by default, the application ID and data directory should stay the same on debug and release builds.

**Comment by WildOrangutan** [comment]
> Contrary to you, I'm fond of being able to test both appstore and development version with the same data on the same device, just by switching the APK.

I don't have the same sign key, so I can't switch between app from store and development, without losing all my settings.

I prefer to run two apps in parallel, so I can potentially compare between them.

Anyways, I do most of manual testing on emulator and my 2nd phone, so I don't particularly care about this :)

**Comment by mathisdt** [comment]
> I don't have the same sign key, so I can't switch between app from store and development, without losing all my settings.
I should've thought of that, sorry. But it's good to hear that you are not particularly sad about this.
