### ISSUE TITLE
Delayed response to detect WLAN

### ISSUE THREAD

**Issue by iceaway** [mathisdt/trackworktime#85]
I'm having problems with Track Work Time getting delayed notifications of my work WLAN becoming available. It takes quite a while for the app to detect my "login" time after I arrive at work. There is usually a 5-15 minute discrepancy between my actual arrival at work, and when the login is detected by TWT. I do not think this is an app issue, since I recently switched to a new phone, and the old one did not have this issue (I used another similar app on the old phone, but that app faces the same issues on my new phone). The new phone is a OnePlus 7T Pro. I have disabled battery optimization for TWT. Any ideas?

**Comment by WildOrangutan** [comment]
Do you have location services enabled (under Settings > Location)? Also check if you have "Wi-Fi scanning" enabled under location. If you don't, let me know if that makes a difference.

If that doesn't help, I'd say android system may be throttling wifi scans. To say for sure, it would be nice if you could share your logs (path: `main_storage/trackworktime/log${dayNumber}.txt`).

As a last resort, you can for a workaround, try disabling WiFi throttling (Developer Options > Networking > Wi-Fi scan throttling). This is new Android 10 feature and it seems like your phone should have it. Tough take care, other apps might drain your battery after that.

**Comment by iceaway** [comment]
I did have location services enabled, but not "Wi-Fi Scanning". Enabled that a couple of days ago, but unfortunately that did not help. 

I'm attaching the logfiles from the phone. I had a look at them myself, and it seems like the "scan request" fails for some reason. For reference, today (2019-12-17), I arrived at work at approximately 6:36, but the detection of my WLAN did not happen until 6:45 (as seen in the logs).

I'm hoping this can be resolved without the potential battery-draining solution. Fingers crossed.

[log.0.txt](https://github.com/mathisdt/trackworktime/files/3971684/log.0.txt)
[log.1.txt](https://github.com/mathisdt/trackworktime/files/3971685/log.1.txt)
[log.txt](https://github.com/mathisdt/trackworktime/files/3971686/log.txt)

**Comment by iceaway** [comment]
I have now also tried disabling WiFi throttling in the Developer Options, but the problem still persists.

**Comment by iceaway** [comment]
I have been looking at the code and logs for a bit, and from what I can tell the only reason the scan should fail, is if it is throttled, since wifi scanning is enabled and there is not likely to be a HW error as the wifi is working well otherwise. That is mysterious since throttling is explicitly disabled in the developer options.

**Comment by WildOrangutan** [comment]
I was able to reproduce your problem on emulator, so it's not related to specific device.

I've double checked wifi scanning implementation with [documentation](https://developer.android.com/guide/topics/connectivity/wifi-scan). Everything looks correct for the time being.
Scanning interval sometimes comes close to 30 seconds, but last 4 scans never exceed documented limitation.
Also checked service at runtime. It also runs correctly in foreground.

There are no major changes documented from Android 9 to 10, which is funny, since scanning is working fine on my Android 9 device.

So atm I'm out of ideas. It's possible this is a bug on their end.

**Comment by iceaway** [comment]
I also studied the documentation and did not find anything strange. Thanks for investigating this issue, hopefully it can be resolved with some future OS upgrade or such.
