### ISSUE TITLE
Ignore flex time for single day

### ISSUE THREAD

**Issue by iceaway** [mathisdt/trackworktime#89]
Last week it was a national holiday on the Monday, and since I did not check into work the flexi time was reduced by all working hours of the day. Is there a way to tell the app that I had the day off, and that the flexi time should not be affected?

**Comment by mathisdt** [comment]
Yes, there is - but it's not in the published version of the app yet. Please see #59 for the gory details, but in short it's a new event type (additional to "start" and "stop") which you can use to define the expected working time for a day. If you place it at 0:00, the day will count as day off and leave your flexi time unaffected if you clock no work. If you place it at 4:00 (while having a normal working time of 8 hours a day), you will have half a day off.

I expect that the new version of the app will be deployed in Google Play Store and F-Droid in the coming weeks, it's in testing at the moment.
