### ISSUE TITLE
Weird flex time total on month boundary, no way to mark "state holidays" or vacation.

### ISSUE THREAD

**Issue by ortylp** [mathisdt/trackworktime#94]
I was happily using the app since mid March, but in the working week 14 (with 1.04. in the middle) The Flex time got somehow resetted on Wednesday.  I think, that doing anything on month boundary should be an option.

Now we have Easter Holidays (Friday and Monday), it means, that weekly target gets reduced from 40 to 32.

Unfortunately the only way to use the app at the moment is to create named backup at the end of the week (optional), write down the flex time, reset the app's data completely, set all options again, enter start flex time and happily use it till next Sunday...

Let me know how can I help in fixing those issues.

**Comment by mathisdt** [comment]
There are multiple possibilities how to handle this. 

1. You can create a new task called e.g. "Vacation" and clock your daily amount of hours for this task on non-working days. This way, you maintain the right flexi time and later, you are able to tell working and non-working days/times apart.

2. There is a relatively new third event type called FLEX which has the mechanics of *setting the expected amount of work for the day to the hour and minute of the event*. So, if you world have a normal daily working time of 8 hours and create a FLEX event at 4:00 am, you only have to clock 4 hours to reach the same flexi time as on the day before. Likewise, if you create a FLEX event at 0:00 am, the flexi time stays the same without work on that day.

For the first option, you can even use "multi-insert" from the menu to handle a time range in one go. The same does not exist for FLEX events, but there is issue #79 which should help when realized.

Feel free to re-open this issue or contacting me directly via the email address on the app's "about" screen if you have more questions!

**Comment by ortylp** [comment]
@mathisdt Thanks for the quick response ;)

The workaround with special task for holidays worked, but only with clocking in and out, not with flex. I assume it would be a bug.

Manual creating new events works only for the default task (the drop down box is grayed out) => Bug?  I could reproduce it only shortly after creating a new task.

The number I was confused about in the first paragraph of the issue (see https://github.com/mathisdt/trackworktime/issues/94#issue-598747572) was about "Worked" column.  This one was miscalculated because I had clock in before midnight and clock out after midnight. The result 16h instead of 40h.  changing this in/out event to two separate ones (clocking out 23::59 and again in at 0:00) seems to fix the issue. => Bug and a nice case for a unittest.

Finally, after "fixing" the above I have seen strange values in flex times...  I have manually triggered backup, resetted apps data, set options (flex, 40h, Mo-Fr), and then reloaded data from backup... For now the "work" and "flex" values seem to be consistent.
