### ISSUE TITLE
Option to disable Log writing

### ISSUE THREAD

**Issue by cwerner1** [mathisdt/trackworktime#97]
Thank you for your work on trackworktime!

I have a feature request: an option to enable/disable the log writing in the data folder.

My Setup: I didn't enable the backup to google. So I setup syncthing to sync the data folder.
Syncthing is always processing the data folder, because the wifi scan are running and the logs ae writen in the folder.

Thanks

**Comment by mathisdt** [comment]
Thanks for your feedback! I also don't use the Google backup but rely on my own [Nextcloud](https://nextcloud.com/) instance. I use [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite) on my phone to sync the data, which also supports setting a name pattern to select the files to sync. This way I don't have to sync the log files.

Maybe this workaround helps you until someone implements this feature request.

**Comment by cwerner1** [comment]
Yes as an work around this works.
Syncthing has alsow the option to ignore files. 
This list must be maintained separately for each device, which makes it a bit more time consuming.

For everyone else with the same Problem:
I added to the .stignore file on the Device the following line:
`*log*`

**Comment by mathisdt** [comment]
This is now obsolete: starting with TWT 1.1.10 (which was released yesterday and should come though F-Droid and the Play store soon), the app uses a new storage approach: the user selects a directory of his liking which TWT uses for backups, automatic backups and reports (each data type in separate subdirectories). The log file is kept in internal memory, but can be manually exported to this shared storage directory (also to a separate subdirectory).
